title: Skills Showcase
email: mateusz.karlowski@zoho.com
markdown: GFM
description: >-
   My skills showcase in one place with practical example using them.
url: "https://mati2251.github.io/" 
baseurl: "skills-showcase" 
github_username:  mati2251
linkedin_username: mateusz-karłowski-8500a1184
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
plugins:
  - jekyll-feed
  - jemoji