title: Skills Showcase
email: mateusz.karlowski@zoho.com
markdown: GFM
description: >-
   Mateusz Karłowski
url: "https://mati2251.github.io" 
baseurl: "skills-showcase" 
github_username:  mati2251
linkedin_username: mateusz-karłowski-8500a1184
remote_theme: pages-themes/minimal@v0.2.0
logo: /asstes/img/logo.png
plugins:
- jekyll-remote-theme
plugins:
  - jekyll-feed
  - jemoji